# List of log files to show
evo_log_viewer:
  log_files:
    # Unique identifier for the logfile
    somelog1:
      # Use full path
      path: 'Some/Full/Path/to/Log/File.Ext'

      # Pretty name to display else file name
      name: My Log Files Pretty Name

      # (Optional) Number of days to pull from log. See ddtraceweb/monolog-parser.
      days: 0

      # (Optional) See ddtraceweb/monolog-parser for patterns.
      pattern: null

      # (Optional) PHP style date format of log file
      date_format: 'Y-m-d H:i:s'

      # (Optional) Use P<channel> in the pattern
      use_channel: true

      # (Optional) Use P<level> in the pattern
      use_level: true

      # (Optional) Log level spelling. Case sensitive
      levels:
        debug: DEBUG
        info: INFO
        notice: NOTICE
        warning: WARNING
        error: ERROR
        alert: ALERT
        critical: CRITICAL
        emergency: EMERGENCY

    somelog2:
      path: '/path/to/logfile.log'
      name: Pretty Logfile Name

  # Show App logs in var/log
  show_app_logs: true

  # (Optional) Change the default parser pattern
  app_pattern: '/\[(?P<date>.*).\d{6}\+\d{2}\:\d{2}\] (?P<channel>\w+).(?P<level>\w+): (?P<message>[^\[\{].*[\]\}])/'

  # (Optional) Change the default date format
  app_date_format: 'Y-m-d\TH:i:s'